name: CI

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18.18

            - name: Install dependencies
              run: npm ci

            - name: Check code formatting with Prettier
              run: npx prettier --check "**/*.{js,ts,json,md}"

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm test

            - name: Check for Changesets
              id: changesets
              run: npx changeset status

            - name: Promote Version if Changeset
              if: steps.changesets.outputs.has-changesets == 'true'
              run: npx changeset version

            - name: Push Changeset Tags
              if: steps.changesets.outputs.has-changesets == 'true'
              run: git push --tags
