name: PR Checks

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        strategy:
            matrix:
                node-version: [16, 18.18, 20.7]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Check code formatting with Prettier
              run: npx prettier --check "**/*.{js,ts,json,md}"

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm test
